Repository mlpack/examples, pull requests merged in 2020-05, with the labels that each got.

#75 Example of possible makefile for mlpack examples
  lstm_electricity_consumption/Makefile
  lstm_stock_prediction/Makefile
  mnist_batch_norm/Makefile
  mnist_cnn/Makefile
  mnist_simple/Makefile
  mnist_vae_cnn/Makefile
Labels: c: examples

#81 Ignore C++ object files, and libraries extensions
  .gitignore
Labels: t: added feature

#82 Remove train time since we have removed declarations before
  mnist_vae_cnn/mnist_vae_cnn.cpp
Labels: c: examples, s: fixed

#83 Simplify Optimizers used in examples.
  lstm_electricity_consumption/lstm_electricity_consumption.cpp
  lstm_stock_prediction/lstm_stock_prediction.cpp
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_cnn/mnist_cnn.cpp
  mnist_simple/mnist_simple.cpp
  mnist_vae_cnn/mnist_vae_cnn.cpp
Labels: c: examples, t: added feature

#87 Use this repo's start year
  LICENSE.txt
Labels: c: documentation

#72 Add LSTM example using Notebooks.
  lstm_stock_prediction/lstm_multivariate_time_series_prediction.ipynb
Labels: c: examples

#73 Add Neural Network Regression example on BodyFat.tsv
  .gitignore
  neural_network_regression/Makefile
  neural_network_regression/neural_network_regression.ipynb
  neural_network_regression/nn_regression.cpp
Labels: c: examples

#91 Use ratml instead of masterblaster to configure armadillo.
  .travis.yml
Labels: c: testing

#90 Added cartpole-dqn notebook
  README.md
  q_learning/cartpole_dqn.ipynb
Labels: c: examples, t: added feature
