Repository mlpack/examples, pull requests merged in 2020-06, with the labels that each got.

#94 Update lstm_stock_prediction.cpp
  lstm_stock_prediction/lstm_stock_prediction.cpp
Labels: s: unanswered, s: unlabeled

#93 Update lstm_electricity_consumption.cpp
  lstm_electricity_consumption/lstm_electricity_consumption.cpp
Labels: c: documentation

#95 Update README
  README.md
Labels: c: documentation, s: unanswered

#96 Download the body fat dataset
  tools/download_data_set.py
Labels: c: examples
