Repository mlpack/examples, pull requests merged in 2020-10, with the labels that each got.

#116 CF MovieLens notebook (C++)
  binder/postBuild
  movie_lens_prediction_with_cf/movie-lens-cf-cpp.ipynb
Labels: c: examples

#124 Ensmallen version check
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_cnn/mnist_cnn.cpp
  mnist_simple/mnist_simple.cpp
  neural_network_regression/nn_regression.cpp
Labels: t: added feature

#126 Return the value from the Lambda.
  mnist_simple/mnist_simple.cpp
Labels: c: examples

#127 Fix paths in some examples.
  lstm_electricity_consumption/lstm_electricity_consumption.cpp
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_simple/mnist_simple.cpp
Labels: c: examples

#125 Update the example with best coordinates callback
  mnist_simple/mnist_simple.cpp
Labels: c: examples

#128 Attempt to run examples on Travis.
  .travis.yml
  README.md
Labels: c: testing

#132 xplot fix
  binder/postBuild
Labels: c: testing
