Repository mlpack/examples, pull requests merged in 2020-11, with the labels that each got.

#133 CI add cereal dependency
  .travis.yml
Labels: c: testing

#119 Try to add cpp files for a reinforcement learning examples
  reinforcement_learning_gym/acrobot_dqn/Makefile
  reinforcement_learning_gym/acrobot_dqn/acrobot_dqn
  reinforcement_learning_gym/acrobot_dqn/acrobot_dqn.cpp
  reinforcement_learning_gym/acrobot_dqn/acrobot_dqn.ipynb
  reinforcement_learning_gym/bipedal_walker_sac/Makefile
  reinforcement_learning_gym/bipedal_walker_sac/bipedal_walker_sac
  reinforcement_learning_gym/bipedal_walker_sac/bipedal_walker_sac.cpp
  reinforcement_learning_gym/bipedal_walker_sac/bipedal_walker_sac.ipynb
  reinforcement_learning_gym/bipedal_walker_sac/sac_policy.txt
  reinforcement_learning_gym/bipedal_walker_sac/sac_q.txt
  reinforcement_learning_gym/cartpole_dqn/Makefile
  reinforcement_learning_gym/cartpole_dqn/cartpole_dqn
  reinforcement_learning_gym/cartpole_dqn/cartpole_dqn.cpp
  reinforcement_learning_gym/cartpole_dqn/cartpole_dqn.ipynb
  reinforcement_learning_gym/gym/CMakeLists.txt
  reinforcement_learning_gym/gym/README.md
  reinforcement_learning_gym/gym/client.hpp
  reinforcement_learning_gym/gym/environment.hpp
  reinforcement_learning_gym/gym/environment_impl.hpp
  reinforcement_learning_gym/gym/example.cpp
  reinforcement_learning_gym/gym/messages.hpp
  reinforcement_learning_gym/gym/monitor.hpp
  reinforcement_learning_gym/gym/monitor_impl.hpp
  reinforcement_learning_gym/gym/parser.hpp
  reinforcement_learning_gym/gym/parser_impl.hpp
  reinforcement_learning_gym/gym/pjson/pjson.h
  reinforcement_learning_gym/gym/space.hpp
  reinforcement_learning_gym/gym/space_impl.hpp
  reinforcement_learning_gym/lunar_lander_dqn/Makefile
  reinforcement_learning_gym/lunar_lander_dqn/lunar_lander_dqn
  reinforcement_learning_gym/lunar_lander_dqn/lunar_lander_dqn.cpp
  reinforcement_learning_gym/lunar_lander_dqn/lunar_lander_dqn.ipynb
  reinforcement_learning_gym/mountain_car_dqn/Makefile
  reinforcement_learning_gym/mountain_car_dqn/mountain_car_dqn
  reinforcement_learning_gym/mountain_car_dqn/mountain_car_dqn.cpp
  reinforcement_learning_gym/mountain_car_dqn/mountain_car_dqn.ipynb
  reinforcement_learning_gym/pendulum_dqn/Makefile
  reinforcement_learning_gym/pendulum_dqn/pendulum_dqn
  reinforcement_learning_gym/pendulum_dqn/pendulum_dqn.cpp
  reinforcement_learning_gym/pendulum_dqn/pendulum_dqn.ipynb
  reinforcement_learning_gym/pendulum_sac/Makefile
  reinforcement_learning_gym/pendulum_sac/pendulum_sac
  reinforcement_learning_gym/pendulum_sac/pendulum_sac.cpp
  reinforcement_learning_gym/pendulum_sac/pendulum_sac.ipynb
Labels: c: examples

#135 Remove boost serialization from Makefile
  lstm_electricity_consumption/Makefile
  lstm_stock_prediction/Makefile
  mnist_batch_norm/Makefile
  mnist_cnn/Makefile
  mnist_simple/Makefile
  mnist_vae_cnn/Makefile
  neural_network_regression/Makefile
Labels: c: examples, s: fixed, s: keep open, t: added feature

#136 Remove unused go plot package to resolve binder build.
  binder/postBuild
Labels: s: fixed

#137 Changes in examples
  .travis.yml
  lstm_stock_prediction/lstm_stock_prediction.cpp
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_vae_cnn/mnist_vae_cnn.cpp
  tools/download_data_set.py
Labels: c: examples

#123 Contact tracing clustering with DBSCAN.
  binder/postBuild
  contact-tracing-dbscan-cpp.ipynb
  contact_tracing_clustering_with_dbscan/contact-tracing-dbscan-cpp.ipynb
Labels: c: examples

#122 Logistic Regression Student Admission notebook (C++).
  student_admission_regression_with_logistic_regression/student-admission-logistic-regression-cpp.ipynb
Labels: c: examples

#139 Recommit contact-tracing-dbscan-cpp.ipynb notebook
  contact_tracing_clustering_with_dbscan/contact-tracing-dbscan-cpp.ipynb
Labels: c: examples
