Repository mlpack/examples, pull requests merged in 2020-07, with the labels that each got.

#89 Adding a clang format to example repository
  .clang-format
  lstm_electricity_consumption/lstm_electricity_consumption.cpp
  lstm_stock_prediction/lstm_stock_prediction.cpp
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_cnn/mnist_cnn.cpp
  mnist_simple/mnist_simple.cpp
  mnist_vae_cnn/mnist_vae_cnn.cpp
  mnist_vae_cnn/vae_utils.hpp
  neural_network_regression/nn_regression.cpp
  tools/fix_style.sh
Labels: c: documentation, t: added feature

#74 Example notebooks
  Project.toml
  binder/Project.toml
  binder/postBuild
  binder/start
  forest_covertype_prediction_with_random_forests/covertype-rf-cpp.ipynb
  forest_covertype_prediction_with_random_forests/covertype-rf-go.ipynb
  forest_covertype_prediction_with_random_forests/covertype-rf-jl.ipynb
  forest_covertype_prediction_with_random_forests/covertype-rf-py.ipynb
Labels: c: examples, s: keep open, t: added feature

#98 Early stop
  mnist_batch_norm/mnist_batch_norm.cpp
  mnist_cnn/mnist_cnn.cpp
  mnist_simple/mnist_simple.cpp
Labels: c: examples, s: needs review, t: added feature

#99 Changes corresponding to mlpack repo in cartpole_dqn
  q_learning/cartpole_dqn.ipynb
Labels: c: examples, t: added feature

#100 Adding notebook for solving acrobot using dqn
  q_learning/acrobot_dqn.ipynb
Labels: c: examples, t: added feature

#103 Adding notebook for solving mountainCar using DQN
  q_learning/mountain_car_dqn.ipynb
Labels: c: examples

#108 Added the pendulum notebook
  q_learning/pendulum_dqn.ipynb
Labels: c: examples

#101 PCA examples
  binder/postBuild
  breast_cancer_wisconsin_transformation_with_pca/breast-cancer-wisconsin-pca-cpp.ipynb
  breast_cancer_wisconsin_transformation_with_pca/breast-cancer-wisconsin-pca-py.ipynb
  cifar10_transformation_with_pca/cifar-10-pca-cpp.ipynb
  cifar10_transformation_with_pca/cifar-10-pca-py.ipynb
Labels: c: examples, t: added feature
