Repository mlpack/examples, pull requests merged in 2020-03, with the labels that each got.

#58 use simpler mlpack cmakelists
  README.md
  appveyor.yml
  mlpack-cmake.patch
Labels: enhancement

#67 Update readme.
  README.md
Labels: c: documentation

#56 Use Ensmallen Callbacks To train LSTM and Fit only on training data.
  LSTM/TimeSeries-Multivariate/src/LSTMTimeSeriesMultivariate.cpp
  LSTM/TimeSeries-Univariate/src/LSTMTimeSeriesUnivariate.cpp
Labels: s: unlabeled
