Repository mlpack/examples, pull requests merged in 2021-06, with the labels that each got.

#156 Fixed segfault of convolutional vae
  mnist_vae_cnn/mnist_vae_cnn.cpp
Labels: s: fixed

#149 Added Linear Regression for predicting salary
  salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
  salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
  tools/download_data_set.py
Labels: c: examples, t: added feature

#157 Samples generating code for Convolutional VAE example
  mnist_vae_cnn/generate_images.py
  mnist_vae_cnn/latent/allSamples.jpg
  mnist_vae_cnn/mnist_vae_cnn.cpp
  mnist_vae_cnn/samples_posterior/allSamples.jpg
  mnist_vae_cnn/samples_prior/2dLatent.jpg
  mnist_vae_cnn/samples_prior/allLatent.jpg
  mnist_vae_cnn/samples_prior/allSamples.jpg
  mnist_vae_cnn/vae_generate.cpp
  mnist_vae_cnn/vae_utils.hpp
Labels: c: examples, t: added feature

#159 Added python notebook for avocado price prediction
  avocado_price_prediction_with_linear_regression/avocado_price_prediction_with_lr_cpp.ipynb
  avocado_price_prediction_with_linear_regression/avocado_price_prediction_with_lr_py.ipynb
  utils/plot.hpp
  utils/plot.py
Labels: c: examples
