Repository mlpack/examples, pull requests merged in 2021-07, with the labels that each got.

#163 Use datasets.mlpack.org as the source for the datasets
  avocado_price_prediction_with_linear_regression/avocado_price_prediction_with_lr_cpp.ipynb
  avocado_price_prediction_with_linear_regression/avocado_price_prediction_with_lr_py.ipynb
  salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
  salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
  tools/download_data_set.py
Labels: c: examples

#164 Added util to print gif
  utils/front.hpp
  utils/front.py
Labels: t: added feature

#160 Refine Portfolio Notebook.
  portfolio_optimization/portfolio-optimization-cpp.ipynb
  portfolio_optimization_nsga2/portfolio-optimization-nsga2-cpp.ipynb
Labels: c: examples

#167 California Housing Price Predictions Notebook
  .gitignore
  california_housing_price_prediction_with_linear_regression/California_housing_prices_predictions_with_lr_python.ipynb
  california_housing_price_prediction_with_linear_regression/california.png
  california_housing_price_prediction_with_linear_regression/california_housing_price_prediction_with_lr_cpp.ipynb
  student_admission_regression_with_logistic_regression/student-admission-logistic-regression-cpp.ipynb
  utils/heatmap.hpp
  utils/heatmap.py
  utils/histogram.hpp
  utils/histogram.py
  utils/impute.hpp
  utils/impute.py
  utils/pandasscatter.hpp
  utils/pandasscatter.py
  utils/plot.hpp
  utils/plot.py
Labels: notebook, t: added feature

#168 Install SoS kernel
  binder/environment.yml
  binder/postBuild
Labels: t: added feature

#165 Rocket injector design optimization
  rocket_injector_design/media/combustion.gif
  rocket_injector_design/media/design.jpg
  rocket_injector_design/media/objectives.jpg
  rocket_injector_design/media/unstable.gif
  rocket_injector_design/rocket-injector-design-cpp.ipynb
Labels: notebook, t: added feature

#170 Added shell script for setting up local environment
  scripts/jupyter-conda-setup.sh
Labels: t: added feature

#162 Added rainfall prediction using Random Forest
  .gitignore
  rainfall_prediction_with_random_forest/rainfall-prediction-with-random-forest-cpp.ipynb
  rainfall_prediction_with_random_forest/rainfall-prediction-with-random-forest-py.ipynb
  utils/plot.hpp
  utils/plot.py
  utils/preprocess.hpp
  utils/preprocess.py
Labels: notebook

#166 Added loan default prediction using Decision tree
  loan_default_prediction_with_decision_tree/loan-default-prediction-with-decision-tree-cpp.ipynb
  loan_default_prediction_with_decision_tree/loan-default-prediction-with-decision-tree-py.ipynb
  utils/plot.py
  utils/preprocess.hpp
  utils/preprocess.py
Labels: notebook, s: needs review
