Repository mlpack/examples, pull requests merged in 2022-08, with the labels that each got.

#203 Mnist CNN Makefile
  mnist_cnn/Makefile
Labels: s: unlabeled, s: unanswered

#204 Update all Makefiles to use C++14.
  cifar10_cnn/Makefile
  lstm_electricity_consumption/Makefile
  lstm_stock_prediction/Makefile
  mnist_batch_norm/Makefile
  mnist_cnn/Makefile
  mnist_simple/Makefile
  mnist_vae_cnn/Makefile
  neural_network_regression/Makefile
  reinforcement_learning_gym/acrobot_dqn/Makefile
  reinforcement_learning_gym/bipedal_walker_sac/Makefile
  reinforcement_learning_gym/cartpole_dqn/Makefile
  reinforcement_learning_gym/lunar_lander_dqn/Makefile
  reinforcement_learning_gym/mountain_car_dqn/Makefile
  reinforcement_learning_gym/pendulum_dqn/Makefile
  reinforcement_learning_gym/pendulum_sac/Makefile
Labels: c: examples

#205 Customer personality clustering
  customer_personality_clustering/customer_personality_clustering_py.ipynb
Labels: notebook
